DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS categories CASCADE;


CREATE TABLE cities (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      city TEXT NOT NULL);

CREATE TABLE categories (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      category TEXT NOT NULL
);

CREATE TABLE resources (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      src_name TEXT NOT NULL,
      src_description TEXT NOT NULL,
      city_id INTEGER NOT NULL REFERENCES cities(id),
      info TEXT [],
      category_id INTEGER FOREIGN KEY REFERENCES categories(id),
      tags TEXT[]
);
